### ISSUE TITLE
☂️New Alert Flow with Native Tabs: Sheet behavior.

### ISSUE THREAD

**Issue by monkeydom** [subethaedit/SubEthaEdit#125]
This is an umbrella bug that will be closed once the new alert flow produces ready for release behaviour.

**Comment by monkeydom** [comment]
Sub-Issue: #106 New Alert Flow: Scheduled alerts don't show up.

**Comment by monkeydom** [comment]
Sub-Issue: #98 Native Tabs: "file has been modified by another application" appears immediately

**Comment by monkeydom** [comment]
Sub-Issue: #127 New Alert System: Revert dialog can be queued multiple times.

**Comment by tolmasky** [comment]
Not sure where the right place to put this is, but the behavior I'm working on in the bigger branch (which shouldn't take much longer to complete) is the following:

1. Document will have an alerts queue (something like `- alerts`)
2. Issuing an alert on a *document* will queue said alert.
3. If it is in a hidden tab (or background ideally), then merely show the alert symbol.
4. If visible, show the sheet.
5. If revealed, then show the sheet
6. This does indeed mean that two identical sheets can be visible at once if you have multiple views on the same document.
7. This is fine, because on interaction with the sheet, this state is trivially propagated to all other sheets:
    A. Ultimately the only "state" that needs to be synchronized is sheet dismissal
    B. So when a sheet is dismissed, the document iterates through all windowControllers, dismissing their identical sheets if present. Otherwise, it removes the alert from the queue so that it won't be shown upon reveal anymore.

I believe this gives the most ideal behavior - it is impossible to us a document that is blocked on an alert until a decision is made, all views of a document show the same alert, and it is impossible to interact with the same sheet twice.

**Comment by monkeydom** [comment]
I like the idea of putting the alert queue on the document, or make it at least managed by the document. And also that all views of a document ideally show the same alert.

I'm not sure if what you propose is enough eventually, e.g. how much follow up work this will generate. E.g. alerts where the outcome is important can't currently just be dismissed. They need to be canceled in a way that the completion isn't called. There is also #127, so eventually this queue should be done in a way that certain types of alert are only queued once. 

On top of that I'm also not quite sure how to best handle the multiple window situation, e.g. now with the native tabs, the sheet is bound to a tab, not to the window of the tab. So we have a different modality than before, this also means that you can switch away from a tab with a sheet to another tab without a sheet, and the sheet is somewhat hidden that way. All flows to be considered and taken care of.

But I guess the patch you are preparing provides a good step in the right direction.

So if this prepared patch is supposed to address #98 (which it sounds like) - please do it as a pull request for #98 and we can take it from there with the other issues. As this umbrella needs to be addressed sufficiently before we can release, progress in smaller steps is good.

**Comment by tolmasky** [comment]
Sorry, just to clarify what I'm imagining in the case of #127, what I mean is that all the "other" (duplicated) sheets can simply be dismissed once any sheet receives confirmation. So the sequence of events would roughly be the following:

1. The "external file changed" event is received and an "alert" is sent to the document (so far identical to the current flow):

```Objective-C
[selfDocument warn:"File was externally whatever, etc."];
```

2. Document has it's internal queue, and internally farms out this sheet to ALL associated windows (pseudo-code here since it also depends on whether the tab is front-most etc, thats what the `canShowSheet` represents here, there is then work to show the sheet on becoming main if it couldn't before, etc.). Critically, the wrapped completion handler dismisses all of these. So it is multiple sheets all connected to one handler:

```Objective-C
@implementation Document

- (void)warn:(NSString *)message then:(Handler)customHandler {

__auto_type coalescedCompletionHandler = ^(responseCode) {
    for (windowController in self.windowControllers) {
        if (windowController.isShowingSheetBoundToThisAlert) {
              // Either use a lock variable or clear the hander so it doesn't call again from here.
             [windowController.window.attachedSheet dismiss];
       }
    }
}

for (windowController in self.windowControllers) {
    if (windowController.canShowSheet) {
         NSAlert * alert = [NSAlert alloc] ...
         [alert beginModalSheetForWindow:windowController completionHandler:coalscedCompletionHandler];
     }
}
```

As you can see, with the above, all the sheets just become "views" of the same "alert". The first one to receive interaction of any sort clears all the rest. Again, the above code removes the actual queue for simplicity.

**Comment by tolmasky** [comment]
Just as a funny aside: in testing to figure this stuff out I realized that Xcode just happily reverts the file without even notifying you, even if you have *unsaved edits*.

**Comment by monkeydom** [comment]
Yeah - our code to detect changes could also be improved. E.g. nowadays as disk-io is quite cheap I even do think we should read the file and compare and only throw up an alert if there are unsaved changes.

**Comment by tolmasky** [comment]
Just wanted to give a quick update that I've got this more or less working now (see video below). Still some stuff to clean up, but hopefully this makes clear what I mean:

https://www.youtube.com/watch?v=cVoDz1vShhI

It will also take time to address the comments made on the PR.

**Comment by tolmasky** [comment]
I now have what I believe to be complete behavior for this. Still have to do some clean up to account for the requests in the last PR, but my goal is to have it all by this weekend.

**Comment by monkeydom** [comment]
Please do update your PR with what you have. I imagine that we need to go back and forth a few times still, and the announcement event is Tuesday already. I'd like to be in a state where I could do an immediate release as soon as possible (And a release in itself takes some extra time in terms of preparation).

**Comment by tolmasky** [comment]
Yeah, makes sense. This is what I'm planning for today. I'll post the completed PR and take down the existing one (since its a part of this larger one), and get the write-up done. It will still have elements that need o bee worked on (namely, I haven't merged the methods back into PlainTextDocument, since it became a mess of merging as the second branch relied on the first, etc.) However, the branch is totally reviewable with this stuff as a separate class (arguably much easier to review actually), and then I can put in the commit that moves it all into the other file tomorrow or so.

**Comment by monkeydom** [comment]
I consider this umbrella done now after 5044afaeb69fa85caa8b194129409892a05f1c9c - further improvements should be filed as separate issues.
