### ISSUE TITLE
Native tabs: Tab related View menu entries appear with first window

### ISSUE THREAD

**Issue by monkeydom** [subethaedit/SubEthaEdit#92]
They should be there from app start.

**Comment by tolmasky** [comment]
If this refers solely to "Show All Tabs" and "Show Tab Bar", it seems to be "by design". I can confirm that this is the behavior in a blank XCode Document-Based Cocoa App that does not open any documents by default (`-applicationShouldOpenUntitledFile:` returns `NO`). Additionally, if you open TextEdit and don't create a new document (hit cancel on the initial open panel), you'll see it is also missing these menu items. It is annoying I agree, but definitely "standard", so might be worth punting.

**Comment by tolmasky** [comment]
Just as an added note, *if* we want these to appear from the start no matter what, it seems like the best bet is to manually add them in the nib. Which is probably fine.

Having stepped through the code `+[NSWindow _addWindowTabsMenuItemsIfNeeded]` is what adds these items at start-up, and does so only if a window is present.

**Comment by monkeydom** [comment]
Yeah - At this point I would identify this behaviour as defect, even if standard.
